security:
  providers:
    dummy_provider:
      id: App\Infrastructure\Security\JWT\DummyUserProvider

  firewalls:
    api:
      pattern: ^/api
      stateless: true
      # Disable the user provider and allow anonymous access to this firewall
      provider: dummy_provider # Explicitly tell Symfony no user provider
      jwt: ~          # Enable JWT for this firewall

  access_control:
    - { path: ^/auth/token, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allow anonymous access to token generation
    - { path: ^/api, roles: ROLE_API } # Secure other API routes
