version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs_php-fpm
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - .:/var/www/symfony
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: cs_nginx
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: cs_mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d/

volumes:
  db_data:
